import "./style/flow.css";
import "./style/react-flow.css";
import "./style/table.css";
import "./style/column-name.scss";
import "./style/info-popup.css";
import "./style/has-one-edge.css";
import "./style/has-many-edge.css";
import "./style/key-icon.css";
import "./style/handle.css";
