import "./style/flow.css";
import "./style/react-flow.scss";
import "./style/table.scss";
import "./style/column-name.scss";
import "./style/info-popup.scss";
import "./style/has-one-edge.scss";
import "./style/has-many-edge.scss";
import "./style/key-icon.css";
import "./style/handle.css";
